async function main() {
    console.log
}

await p.then((valor) => {
    console.log(valor)
}).catch((erro) => {
    console.log(erro)
})

console.log(1)
console.log(2)
console.log(3)